obj-m += arm-pgtable-walk.o

all:
	make -C /home/zhang/research/imx53/linux-2.6-imx-imx_2.6.35_maintain/ M=$(PWD) modules

clean:
	make -C /home/zhang/research/imx53/linux-2.6-imx-imx_2.6.35_maintain/ M=$(PWD) clean
